// packages/core/tests/sort-worker-code.test.ts
// SORT_WORKER_CODE is generated from sort-worker.script.ts by
// scripts/build-worker.ts (regenerated by tests/global-setup.ts before this
// suite runs). These tests execute the generated script in a fake worker
// scope, since the DOM `Worker` global is unavailable under Node.

import { describe, it, expect } from "vitest";
import { SORT_WORKER_CODE } from "../src/sorting/sort-worker-code";
import type { SortWorkerMessage } from "../src/sorting/sort-worker-messages";

interface FakeScope {
  onmessage: ((event: { data: SortWorkerMessage }) => void) | null;
  postMessage: (message: Record<string, unknown>, transfer?: Transferable[]) => void;
}

/** Evaluate the worker script against a fake `self`; returns a request → response helper. */
const bootWorker = () => {
  const posted: Record<string, unknown>[] = [];
  const scope: FakeScope = {
    onmessage: null,
    postMessage: (message) => {
      posted.push(message);
    },
  };
  new Function("self", SORT_WORKER_CODE)(scope);
  return (request: SortWorkerMessage): Record<string, unknown> => {
    scope.onmessage?.({ data: request });
    return posted.pop() ?? {};
  };
};

describe("SORT_WORKER_CODE", () => {
  it("is minified: single line, no comments", () => {
    expect(SORT_WORKER_CODE).not.toContain("\n");
    expect(SORT_WORKER_CODE).not.toContain("//");
  });

  it("sorts rows by a nested field", () => {
    const send = bootWorker();
    const data = [{ a: { n: 3 } }, { a: { n: 1 } }, { a: { n: 2 } }];
    const response = send({ type: "sort", id: 1, data, sortModel: [{ colId: "a.n", direction: "desc" }] });
    expect(response.type).toBe("sorted");
    expect(response.id).toBe(1);
    expect(response.data).toEqual([{ a: { n: 3 } }, { a: { n: 2 } }, { a: { n: 1 } }]);
  });

  it("sorts a numeric chunk stably and echoes the offset", () => {
    const send = bootWorker();
    const values = new Float64Array([5, 1, 5, 0]);
    const response = send({ type: "sortChunk", id: 2, values, direction: "asc", chunkOffset: 40 });
    expect(response.type).toBe("sortedChunk");
    expect(Array.from(response.indices as Uint32Array)).toEqual([3, 1, 0, 2]);
    expect(Array.from(response.sortedValues as Float64Array)).toEqual([0, 1, 5, 5]);
    expect(response.chunkOffset).toBe(40);
  });

  it("reports collision runs for identical string hashes", () => {
    const send = bootWorker();
    const hashChunks = [new Float64Array([7, 7, 2, 7])];
    const response = send({ type: "sortStringHashes", id: 3, hashChunks, direction: "asc" });
    expect(Array.from(response.indices as Uint32Array)).toEqual([2, 0, 1, 3]);
    expect(Array.from(response.collisionRuns as Uint32Array)).toEqual([1, 4]);
  });

  it("answers with an error message instead of throwing", () => {
    const send = bootWorker();
    const response = send({ type: "sortMultiColumn", id: 4, columns: [], directions: new Int8Array() });
    expect(response.type).toBe("error");
    expect(response.id).toBe(4);
    expect(typeof response.error).toBe("string");
  });
});
