// packages/core/scripts/build-worker.ts
// Bundles the typed sort worker (src/sorting/sort-worker.script.ts) into a
// minified, self-contained script string and writes it to
// src/sorting/sort-worker-code.ts as `SORT_WORKER_CODE`.
//
// The generated file is a build artifact and is git-ignored. It is (re)created:
//   - on `pnpm install`            → core "prepare" script
//   - before every tsdown build    → build:prepare hook in tsdown.config.ts
//   - before the vitest suite      → tests/global-setup.ts
//   - manually                     → `pnpm build:worker`
// CI builds core before testing and publishing (npm + JSR), so the artifact is
// always present where it is needed.

import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "tsdown";

const packageRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const WORKER_ENTRY = resolve(packageRoot, "src/sorting/sort-worker.script.ts");
const WORKER_MODULE = resolve(packageRoot, "src/sorting/sort-worker-code.ts");

/** Bundle + minify the worker entry into a single IIFE script (in memory, nothing written). */
export const bundleSortWorker = async (): Promise<string> => {
  const [bundle] = await build({
    config: false, // standalone: do not load tsdown.config.ts (which imports this file)
    cwd: packageRoot,
    entry: WORKER_ENTRY,
    platform: "browser",
    format: "iife",
    minify: true,
    dts: false,
    write: false,
    clean: false,
    logLevel: "silent",
  });
  if (!bundle) throw new Error("tsdown produced no bundle for the sort worker");
  const chunk = bundle.chunks.find((c) => c.type === "chunk");
  if (!chunk) throw new Error("tsdown produced no code chunk for the sort worker");
  return chunk.code;
};

/** Render the TypeScript module that exports the script as a string constant. */
export const renderSortWorkerModule = (code: string): string =>
  [
    "// packages/core/src/sorting/sort-worker-code.ts",
    "// GENERATED by scripts/build-worker.ts from sort-worker.script.ts — do not edit.",
    "// Regenerate with `pnpm build:worker` (also runs on every `pnpm build`).",
    "",
    "/** Minified, self-contained sort worker script; WorkerPool loads it via a Blob URL. */",
    `export const SORT_WORKER_CODE: string = ${JSON.stringify(code)};`,
    "",
  ].join("\n");

/** Regenerate sort-worker-code.ts. Returns true when the file changed. */
export const writeSortWorkerModule = async (): Promise<boolean> => {
  const next = renderSortWorkerModule(await bundleSortWorker());
  const previous = existsSync(WORKER_MODULE) ? readFileSync(WORKER_MODULE, "utf8") : "";
  if (previous === next) return false;
  writeFileSync(WORKER_MODULE, next);
  return true;
};

if (import.meta.main) {
  const changed = await writeSortWorkerModule();
  console.log(changed ? "✓ sort-worker-code.ts regenerated" : "✓ sort-worker-code.ts up to date");
}
